### ISSUE TITLE
"python -m pip install" troubles

### ISSUE THREAD

**Issue by Cbhihe** [openai/CLIP#168]
Hi all, I have an issue that I already I spent a few hours troubleshooting. At this point, I am stumped.  **Help would be really welcome !**

I am trying to install CLIP with pip only to get an error with "exit status -11". The url `https://github.com/openai/CLIP.git` is correctly resolved and the cloning takes place.  Right after that something happens, apparently when `setup.py` is invoked.
I install CLIP in a directory that is configured as a Python 3.7.0 virtual environment created with  `pyenv`.

```
$ python -m  pip install git+https://github.com/openai/CLIP.git
[Output]
Collecting git+https://github.com/openai/CLIP.git
  Cloning https://github.com/openai/CLIP.git to /tmp/pip-req-build-a9w5r74y
  Running command git clone --filter=blob:none -q https://github.com/openai/CLIP.git /tmp/pip-req-build-a9w5r74y
  Resolved https://github.com/openai/CLIP.git to commit e184f608c5d5e58165682f7c332c3a8b4c1545f2
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status -11:
   command: /home/USER/.pyenv/versions/3.7.0/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-a9w5r74y/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-a9w5r74y/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ok169mzm
       cwd: /tmp/pip-req-build-a9w5r74y/
  Complete output (0 lines):
  ----------------------------------------
WARNING: Discarding git+https://github.com/openai/CLIP.git. Command errored out with exit status -11: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status -11: python setup.py egg_info Check the logs for full command output.
```
Looking at past issues on this same forum, I also attempted to clone the git repo and to install directly with:
```
$ git clone https://github.com/openai/CLIP.git
$ cd CLIP
$ python -m pip install .
```
... only to get the exact same error message. **_

The pip log I collected follows. 
```
$ python setup.py egg_info
running egg_info
writing clip.egg-info/PKG-INFO
writing dependency_links to clip.egg-info/dependency_links.txt
writing requirements to clip.egg-info/requires.txt
writing top-level names to clip.egg-info/top_level.txt
file clip.py (for module clip) not found
reading manifest file 'clip.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'clip.egg-info/SOURCES.txt'
```

Looking at some of the output for instance `clip.egg-info/requires.txt`:
```
$ cat clip.egg-info/requires.txt
ftfy
regex
tqdm
torch
torchvision

[dev]
pytest
```
Those and other requirements are all satisfied so the issue may be elsewhere:
```
$ python -m pip list | grep -E "ftfy|regex|tqdm|torch|torchvision"
ftfy               6.0.3
regex              2021.10.23
torch              1.7.1+cpu
torchaudio         0.7.2
torchvision        0.8.2+cpu
tqdm               4.62.3
```
--------------------------------------------------------------------------------------------------
**PIP.LOG**

```
2021-10-28T19:56:58,844 Using pip 21.3.1 from /home/USER/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pip (python 3.7)
2021-10-28T19:56:58,845 Non-user install because site-packages writeable
2021-10-28T19:56:58,891 Created temporary directory: /tmp/pip-ephem-wheel-cache-62nvqpgg
2021-10-28T19:56:58,891 Created temporary directory: /tmp/pip-req-tracker-ipv9yf7q
2021-10-28T19:56:58,891 Initialized build tracking at /tmp/pip-req-tracker-ipv9yf7q
2021-10-28T19:56:58,891 Created build tracker: /tmp/pip-req-tracker-ipv9yf7q
2021-10-28T19:56:58,891 Entered build tracker: /tmp/pip-req-tracker-ipv9yf7q
2021-10-28T19:56:58,891 Created temporary directory: /tmp/pip-install-zikyepxt
2021-10-28T19:56:58,903 Collecting git+https://github.com/openai/CLIP.git
2021-10-28T19:56:58,903   Created temporary directory: /tmp/pip-req-build-j7yt1e41
2021-10-28T19:56:58,904   Cloning https://github.com/openai/CLIP.git to /tmp/pip-req-build-j7yt1e41
2021-10-28T19:56:58,904   Running command git version
2021-10-28T19:56:58,907   git version 2.33.1
2021-10-28T19:56:58,907   Running command git clone --filter=blob:none -q https://github.com/openai/CLIP.git /tmp/pip-req-build-j7yt1e41
2021-10-28T19:57:00,915   Running command git rev-parse HEAD
2021-10-28T19:57:00,918   e184f608c5d5e58165682f7c332c3a8b4c1545f2
2021-10-28T19:57:00,918   Resolved https://github.com/openai/CLIP.git to commit e184f608c5d5e58165682f7c332c3a8b4c1545f2
2021-10-28T19:57:00,918   Added git+https://github.com/openai/CLIP.git to build tracker '/tmp/pip-req-tracker-ipv9yf7q'
2021-10-28T19:57:00,919   Running setup.py (path:/tmp/pip-req-build-j7yt1e41/setup.py) egg_info for package from git+https://github.com/openai/CLIP.git
2021-10-28T19:57:00,919   Created temporary directory: /tmp/pip-pip-egg-info-0p6whb2h
2021-10-28T19:57:00,919   Running command python setup.py egg_info
2021-10-28T19:57:01,221 WARNING: Discarding git+https://github.com/openai/CLIP.git. Command errored out with exit status -11: python setup.py egg_info Check the logs for full command output.
2021-10-28T19:57:01,222 ERROR: Command errored out with exit status -11: python setup.py egg_info Check the logs for full command output.
2021-10-28T19:57:01,222 Exception information:
2021-10-28T19:57:01,222 Traceback (most recent call last):
2021-10-28T19:57:01,222   File "/home/USER/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 164, in exc_logging_wrapper
2021-10-28T19:57:01,222     status = run_func(*args)
2021-10-28T19:57:01,222   File "/home/USER/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
2021-10-28T19:57:01,222     return func(self, options, args)
2021-10-28T19:57:01,222   File "/home/USER/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 339, in run
2021-10-28T19:57:01,222     reqs, check_supported_wheels=not options.target_dir
2021-10-28T19:57:01,222   File "/home/USER/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 73, in resolve
2021-10-28T19:57:01,222     collected = self.factory.collect_root_requirements(root_reqs)
2021-10-28T19:57:01,222   File "/home/USER/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 470, in collect_root_requirements
2021-10-28T19:57:01,222     requested_extras=(),
2021-10-28T19:57:01,222   File "/home/USER/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 445, in _make_requirement_from_install_req
2021-10-28T19:57:01,222     raise self._build_failures[ireq.link]
2021-10-28T19:57:01,222   File "/home/USER/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
2021-10-28T19:57:01,222     version=version,
2021-10-28T19:57:01,222   File "/home/USER/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 287, in __init__
2021-10-28T19:57:01,222     version=version,
2021-10-28T19:57:01,222   File "/home/USER/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
2021-10-28T19:57:01,222     self.dist = self._prepare()
2021-10-28T19:57:01,222   File "/home/USER/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
2021-10-28T19:57:01,222     dist = self._prepare_distribution()
2021-10-28T19:57:01,222   File "/home/USER/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 292, in _prepare_distribution
2021-10-28T19:57:01,222     return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
2021-10-28T19:57:01,222   File "/home/USER/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 482, in prepare_linked_requirement
2021-10-28T19:57:01,222     return self._prepare_linked_requirement(req, parallel_builds)
2021-10-28T19:57:01,222   File "/home/USER/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 550, in _prepare_linked_requirement
2021-10-28T19:57:01,222     self.build_isolation,
2021-10-28T19:57:01,222   File "/home/USER/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 58, in _get_prepared_distribution
2021-10-28T19:57:01,222     abstract_dist.prepare_distribution_metadata(finder, build_isolation)
2021-10-28T19:57:01,222   File "/home/USER/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pip/_internal/distributions/sdist.py", line 49, in prepare_distribution_metadata
2021-10-28T19:57:01,222     self.req.prepare_metadata()
2021-10-28T19:57:01,222   File "/home/USER/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 566, in prepare_metadata
2021-10-28T19:57:01,222     details=self.name or f"from {self.link}",
2021-10-28T19:57:01,222   File "/home/USER/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 63, in generate_metadata
2021-10-28T19:57:01,222     spinner=spinner,
2021-10-28T19:57:01,222   File "/home/USER/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pip/_internal/utils/subprocess.py", line 254, in call_subprocess
2021-10-28T19:57:01,222     raise InstallationSubprocessError(proc.returncode, command_desc)
2021-10-28T19:57:01,222 pip._internal.exceptions.InstallationSubprocessError: Command errored out with exit status -11: python setup.py egg_info Check the logs for full command output.
2021-10-28T19:57:01,242 Removed git+https://github.com/openai/CLIP.git from build tracker '/tmp/pip-req-tracker-ipv9yf7q'
2021-10-28T19:57:01,242 Removed build tracker: '/tmp/pip-req-tracker-ipv9yf7q'
```

**Comment by jongwook** [comment]
From the log, it looks like `python setup.py egg_info` is failing for some reason.

As a workaround, you could copy the `clip` directory from this repo to your local directory, instead of going through pip.

**Comment by Cbhihe** [comment]
Hi Jongwook, thank you for taking the time to review the log and to respond.  Some 20 days ago, rather despairing of kick-starting this I alctually reinstalled everything with first a Python 3.7.5 and second a Python 3.7.1 virtual environment.   The Python 3.7.1 install has worked quite smoothly so far, and it looks like the issue was one of versioning.  Many cheers !
