### ISSUE TITLE
error when pip install git+https://github.com/openai/CLIP.git

### ISSUE THREAD

**Issue by kennethliukai** [openai/CLIP#90]
(base) liukai@liukaideMacBook-Pro Downloads % pip install git+https://github.com/openai/CLIP.git
Collecting git+https://github.com/openai/CLIP.git
  Cloning https://github.com/openai/CLIP.git to /private/var/folders/kr/v9ktnnhn5f11s9pp5977pwqr0000gn/T/pip-req-build-52s9sqhl
ERROR: Command errored out with exit status 128: git clone -q https://github.com/openai/CLIP.git /private/var/folders/kr/v9ktnnhn5f11s9pp5977pwqr0000gn/T/pip-req-build-52s9sqhl Check the logs for full command output.

But I can access https://github.com/openai/CLIP.git in chrome. Anyone can help, thanks

**Comment by jongwook** [comment]
Does it happen after retrying, and if so, can you post the pip log? You may append `--log pip-log.txt` to the pip command to save a log to `pip-log.txt`.

**Comment by kennethliukai** [comment]
> Does it happen after retrying, and if so, can you post the pip log? You may append `--log pip-log.txt` to the pip command to save a log to `pip-log.txt`.

Thanks for your reply. I retried several times but it happen in every time. Here are the logs:

2021-04-12T09:51:27,616 Using pip 20.2.4 from /Users/liukai/opt/anaconda3/lib/python3.8/site-packages/pip (python 3.8)
2021-04-12T09:51:27,618 Non-user install because site-packages writeable
2021-04-12T09:51:27,664 Created temporary directory: /private/var/folders/kr/v9ktnnhn5f11s9pp5977pwqr0000gn/T/pip-ephem-wheel-cache-8l_nt8yh
2021-04-12T09:51:27,664 Created temporary directory: /private/var/folders/kr/v9ktnnhn5f11s9pp5977pwqr0000gn/T/pip-req-tracker-e848dc1k
2021-04-12T09:51:27,664 Initialized build tracking at /private/var/folders/kr/v9ktnnhn5f11s9pp5977pwqr0000gn/T/pip-req-tracker-e848dc1k
2021-04-12T09:51:27,664 Created build tracker: /private/var/folders/kr/v9ktnnhn5f11s9pp5977pwqr0000gn/T/pip-req-tracker-e848dc1k
2021-04-12T09:51:27,664 Entered build tracker: /private/var/folders/kr/v9ktnnhn5f11s9pp5977pwqr0000gn/T/pip-req-tracker-e848dc1k
2021-04-12T09:51:27,665 Created temporary directory: /private/var/folders/kr/v9ktnnhn5f11s9pp5977pwqr0000gn/T/pip-install-fi1s2h_4
2021-04-12T09:51:27,667 Collecting git+https://github.com/openai/CLIP.git
2021-04-12T09:51:27,668   Created temporary directory: /private/var/folders/kr/v9ktnnhn5f11s9pp5977pwqr0000gn/T/pip-req-build-ez7cejzc
2021-04-12T09:51:27,668   Cloning https://github.com/openai/CLIP.git to /private/var/folders/kr/v9ktnnhn5f11s9pp5977pwqr0000gn/T/pip-req-build-ez7cejzc
2021-04-12T09:56:10,582 ERROR: Command errored out with exit status 128: git clone -q https://github.com/openai/CLIP.git /private/var/folders/kr/v9ktnnhn5f11s9pp5977pwqr0000gn/T/pip-req-build-ez7cejzc Check the logs for full command output.
2021-04-12T09:56:10,583 Exception information:
2021-04-12T09:56:10,583 Traceback (most recent call last):
2021-04-12T09:56:10,583   File "/Users/liukai/opt/anaconda3/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
2021-04-12T09:56:10,583     status = self.run(options, args)
2021-04-12T09:56:10,583   File "/Users/liukai/opt/anaconda3/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
2021-04-12T09:56:10,583     return func(self, options, args)
2021-04-12T09:56:10,583   File "/Users/liukai/opt/anaconda3/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 323, in run
2021-04-12T09:56:10,583     requirement_set = resolver.resolve(
2021-04-12T09:56:10,583   File "/Users/liukai/opt/anaconda3/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve
2021-04-12T09:56:10,583     discovered_reqs.extend(self._resolve_one(requirement_set, req))
2021-04-12T09:56:10,583   File "/Users/liukai/opt/anaconda3/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 388, in _resolve_one
2021-04-12T09:56:10,583     abstract_dist = self._get_abstract_dist_for(req_to_install)
2021-04-12T09:56:10,583   File "/Users/liukai/opt/anaconda3/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 340, in _get_abstract_dist_for
2021-04-12T09:56:10,583     abstract_dist = self.preparer.prepare_linked_requirement(req)
2021-04-12T09:56:10,583   File "/Users/liukai/opt/anaconda3/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 467, in prepare_linked_requirement
2021-04-12T09:56:10,583     local_file = unpack_url(
2021-04-12T09:56:10,583   File "/Users/liukai/opt/anaconda3/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 239, in unpack_url
2021-04-12T09:56:10,583     unpack_vcs_link(link, location)
2021-04-12T09:56:10,583   File "/Users/liukai/opt/anaconda3/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 99, in unpack_vcs_link
2021-04-12T09:56:10,583     vcs_backend.unpack(location, url=hide_url(link.url))
2021-04-12T09:56:10,583   File "/Users/liukai/opt/anaconda3/lib/python3.8/site-packages/pip/_internal/vcs/versioncontrol.py", line 733, in unpack
2021-04-12T09:56:10,583     self.obtain(location, url=url)
2021-04-12T09:56:10,583   File "/Users/liukai/opt/anaconda3/lib/python3.8/site-packages/pip/_internal/vcs/versioncontrol.py", line 641, in obtain
2021-04-12T09:56:10,583     self.fetch_new(dest, url, rev_options)
2021-04-12T09:56:10,583   File "/Users/liukai/opt/anaconda3/lib/python3.8/site-packages/pip/_internal/vcs/git.py", line 230, in fetch_new
2021-04-12T09:56:10,583     self.run_command(make_command('clone', '-q', url, dest))
2021-04-12T09:56:10,583   File "/Users/liukai/opt/anaconda3/lib/python3.8/site-packages/pip/_internal/vcs/versioncontrol.py", line 771, in run_command
2021-04-12T09:56:10,583     return call_subprocess(cmd, cwd,
2021-04-12T09:56:10,583   File "/Users/liukai/opt/anaconda3/lib/python3.8/site-packages/pip/_internal/vcs/versioncontrol.py", line 166, in call_subprocess
2021-04-12T09:56:10,583     raise SubProcessError(exc_msg)
2021-04-12T09:56:10,583 pip._internal.exceptions.SubProcessError: Command errored out with exit status 128: git clone -q https://github.com/openai/CLIP.git /private/var/folders/kr/v9ktnnhn5f11s9pp5977pwqr0000gn/T/pip-req-build-ez7cejzc Check the logs for full command output.
2021-04-12T09:56:10,701 Removed build tracker: '/private/var/folders/kr/v9ktnnhn5f11s9pp5977pwqr0000gn/T/pip-req-tracker-e848dc1k'

**Comment by jongwook** [comment]
It's not clear from those logs why exactly git clone fails under `pip install`, but it could be some certificate setting issue.

Can you try the following to clone the repo locally and do a manual install of the package?

```bash
git clone https://github.com/openai/CLIP.git
cd CLIP
pip install .
```

**Comment by develop-productivity** [comment]
`pip install git+https://github.com/openai/CLIP.git` Can use the conda command instead this command?

**Comment by sallymmx** [comment]
您好，我是王蒙蒙，您的邮件我已收到，并及时回复。
